# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

stages:
- stage: Build 
  displayName: 'Docker Build/Push Stage'
  jobs:
  - job: BuildJob
    
    steps:
      - task: Docker@2
        displayName: 'Docker Build'
        inputs:
          containerRegistry: 'DockerSC'
          repository: 'advikbalan2709/helloworld'
          command: 'build'
          Dockerfile: '**/Dockerfile.linux'
          tags: |
            $(Build.BuildId)

      - task: Docker@2
        displayName: 'Docker Push'
        inputs:
          containerRegistry: 'DockerSC'
          repository: 'advikbalan2709/helloworld'
          command: 'push'
          tags: |
            $(Build.BuildId)



- stage: Deploy
  displayName: 'Deploy to AKS'
  dependsOn: Build  # Ensure this stage waits for the Build stage to complete
  jobs:
  - job: DeployJob
    displayName: 'Deploy to AKS'
    steps:
      - task: KubernetesManifest@1
        displayName: 'Deploy to AKS using Canary Strategy'
        inputs:
          action: 'deploy'
          connectionType: 'Azure Resource Manager'
          azureSubscription: 'AzureSC'  # Service connection name for Azure subscription
          azureResourceGroup: 'aks'
          kubernetesCluster: 'aks-demo-cluster'
          namespace: 'dev'
          strategy: 'canary'  # Deployment strategy
          percentage: '50'  # Percentage for canary deployment
          manifests: 'manifests/*'  # Path to Kubernetes manifests