# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

stages:
- stage: Build 
  displayName: 'Docker Build/Push Stage'
  jobs:
  - job: BuildJob
    
    steps:
      - task: Docker@2
        displayName: 'Docker Build'
        inputs:
          containerRegistry: 'DockerSC'
          repository: 'advikbalan2709/helloworld'
          command: 'build'
          Dockerfile: '**/Dockerfile.linux'
          tags: |
            $(Build.BuildId)

      - task: Docker@2
        displayName: 'Docker Push'
        inputs:
          containerRegistry: 'DockerSC'
          repository: 'advikbalan2709/helloworld'
          command: 'push'
          tags: |
            $(Build.BuildId)



- stage: Deploy
  displayName: 'Deploy to AKS'
  dependsOn:[build]
    jobs:
      - job: DeployJob
        
        steps:
        - task: KubernetesManifest@1
          inputs:
            action: 'deploy'
            connectionType: 'azureResourceManager'
            azureSubscriptionConnection: 'AzureSC'
            azureResourceGroup: 'aks'
            kubernetesCluster: 'aks-demo-cluster'
            namespace: 'dev'
            strategy: 'canary'
            percentage: '50'
            manifests: '*'
          

