# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

steps:

  - task: Docker@2
    inputs:
      containerRegistry: 'DockerSC'
      repository: 'advikbalan2709/helloworld'
      command: 'build'
      Dockerfile: '**/Dockerfile.linux'
      tags: |
        $(Build.BuildId)
        

