# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

stages:
- stage: Build 
  displayName: 'Docker Build/Push Stage'
  jobs:
  - job: BuildJob
    
    steps:
      - task: Docker@2
        displayName: 'Docker Build'
        inputs:
          containerRegistry: 'DockerSC'
          repository: 'advikbalan2709/helloworld'
          command: 'build'
          Dockerfile: '**/Dockerfile.linux'
          tags: |
            $(Build.BuildId)

      - task: Docker@2
        displayName: 'Docker Push'
        inputs:
          containerRegistry: 'DockerSC'
          repository: 'advikbalan2709/helloworld'
          command: 'push'
          tags: |
            $(Build.BuildId)



- stage: Deploy
  displayName: 'Deploy to AKS'
  dependsOn: Build
  jobs:
  - job: DeployJob
    displayName: 'Deploy to AKS'
    variables:
      BUILD_ID: $(Build.BuildId)  # Pass the build ID as a variable
    steps:
      - task: Bash@3
        displayName: 'Update Deployment Manifest with Build ID'
        inputs:
          targetType: 'inline'
          script: |
            sed -i 's/BUILD_ID_PLACEHOLDER/$(BUILD_ID)/g' $(deploymentPath)

      - task: KubernetesManifest@1
        displayName: 'Deploy to AKS using Canary Strategy'
        inputs:
          action: 'deploy'
          connectionType: 'Azure Resource Manager'
          azureSubscription: 'AzureSC'
          azureResourceGroup: 'aks'
          kubernetesCluster: 'aks-demo-cluster'
          namespace: 'dev'
          strategy: 'canary'
          percentage: '50'
          manifests: $(deploymentPath)
