apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
    app: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: advikbalan2709/helloworld:BUILD_ID_PLACEHOLDER  # Replace 'latest' with your specific tag if needed
        ports:
        - containerPort: 80
      