apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-microservice
  namespace: microservice
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sample-microservice
  namespace: microservice
subjects:
  - kind: ServiceAccount
    name: sample-microservice
roleRef:
  kind: Role
  name: sample-microservice
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-microservice
  namespace: microservice
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sample-microservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        prometheus.io/scrape: "true"
        aadpodidbinding: id-cw-sample-microservice
        app: sample-microservice
    spec:
      containers:
        - image: $IMAGE
          imagePullPolicy: Always
          name: sample-microservice
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 400m
              memory: 400Mi
            requests:
              cpu: 200m
              memory: 201Mi
          securityContext:
            allowPrivilegeEscalation: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/config/versions
              name: services-versions-volume
            - mountPath: /var/logs
              name: tmpfs-1
      serviceAccountName: sample-microservice